name: Run Gradle on PRs
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: sdk-dist/kotlin