# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish SDK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
        working-directory: etd-sdk-generator
      - run: yarn start
        working-directory: etd-sdk-generator

  publish-kotlin:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: sdk-dist/kotlin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./sdk-dist/kotlin/build/distributions/
            ./sdk-dist/kotlin/build/libs/


  publish-typescript-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Installing dependencies
        working-directory: sdk-dist/typescript
      - run: yarn build
        name: Building dist
        working-directory: sdk-dist/typescript
      - run: yarn publish
        name: Publishing sdk
        working-directory: sdk-dist/typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-react-ui-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Installing dependencies
        working-directory: sdk-dist/etd-react-ui
      - run: yarn build
        name: Building dist
        working-directory: sdk-dist/etd-react-ui
      - run: yarn publish
        name: Publishing sdk
        working-directory: sdk-dist/etd-react-ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}