# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish SDK

on:
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
        working-directory: etd-sdk-generator
      - run: yarn start
        working-directory: etd-sdk-generator

  publish-kotlin:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: sdk-dist/kotlin
      - uses: gradle/gradle-build-action@v2
        name: Building Kotlin Docs
        with:
          arguments: dokkaHtml
          build-root-directory: sdk-dist/kotlin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./sdk-dist/kotlin/build/distributions/etd-sdk-${{ env.RELEASE_VERSION }}.tar
            ./sdk-dist/kotlin/build/distributions/etd-sdk-${{ env.RELEASE_VERSION }}.zip
            ./sdk-dist/kotlin/build/libs/etd-sdk-${{ env.RELEASE_VERSION }}.jar

      - uses: actions/upload-artifact@v2
        with:
          name: kotlin-doc
          path: ./sdk-dist/kotlin/build/dokka/html
          retention-days: 1


  publish-typescript-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Installing dependencies
        working-directory: sdk-dist/typescript
      - run: yarn build
        name: Building dist
        working-directory: sdk-dist/typescript
      - run: yarn doc
        name: Building documentation
        working-directory: sdk-dist/typescript
      - uses: actions/upload-artifact@v2
        with:
          name: js-doc
          path: docs/docs/typescript/api
          retention-days: 1
      - run: yarn publish
        name: Publishing sd
        working-directory: sdk-dist/typescript
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-react-ui-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Installing dependencies
        working-directory: sdk-dist/etd-react-ui
      - run: yarn build
        name: Building dist
        working-directory: sdk-dist/etd-react-ui
      - run: yarn publish
        name: Publishing sdk
        working-directory: sdk-dist/etd-react-ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-docs:
    needs:
      - publish-kotlin
      - publish-typescript-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve JS Docs
        uses: actions/download-artifact@v2
        with:
          name: js-doc
          path: docs/docs/typescript/api
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn
        name: Installing dependencies
        working-directory: docs
      - run: yarn build
        name: Building website
        working-directory: docs
      - name: Retrieve Kotlin Docs
        uses: actions/download-artifact@v2
        with:
          name: kotlin-doc
          path: docs/build/docs/kotlin/api
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
