# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
        working-directory: etd-sdk-generator
      - run: yarn start
        working-directory: etd-sdk-generator
      - run: yarn
        name: Installing Typescript SDK Dependencies
        working-directory: sdk-dist/typescript
      - run: yarn test
        name: Testing Typescript SDK
        working-directory: sdk-dist/typescript
        env:
          httpsUrl: https://debug.etdchain.net/hdkEtd@Themoon
